name: 🔱 AKAME: FORJA SOBERANA
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonando
        uses: actions/checkout@v4
      - name: ☕ Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: ⚙️ Gerando Motor
        run: gradle wrapper --gradle-version 8.2
      - name: 🏗️ Compilando APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: 📤 ENTREGAR APK
        uses: actions/upload-artifact@v4
        with:
          name: Akame_Soberana_V3
          path: app/build/outputs/apk/debug/*.apk
