name: 🔱 AKAME: FORJA SOBERANA V2
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonando
        uses: actions/checkout@v4
      - name: ⚙️ Akame: Autocriação
        run: chmod +x akame_build_core.sh && ./akame_build_core.sh
      - name: ☕ Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 🏗️ Compilando
        run: |
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: 📤 ENTREGAR
        uses: actions/upload-artifact@v4
        with:
          name: Akame_V2_Pronta
          path: app/build/outputs/apk/debug/*.apk
