name: 🔱 FORJA OMNI (Compilação e Entrega)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - name: 🛰️ Clonando DNA
        uses: actions/checkout@v4
      
      - name: ☕ Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🔑 Permissão
        run: chmod +x gradlew

      - name: 🛠️ Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: 📦 Entrega
        uses: actions/upload-artifact@v4
        with:
          name: Akame_Soberana_Final
          path: "**/build/outputs/apk/debug/*.apk"
