name: 🔱 FORJA OMNI AKAME
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 🔱 VALIDAR GRADLE
        run: gradle wrapper --gradle-version 8.5
      - name: 🔱 FORJAR APK
        run: chmod +x gradlew && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Akame_V35_APK
          path: app/build/outputs/apk/debug/app-debug.apk
